<!--
document.write('<DIV id=submenu_01 style="DISPLAY: none"">');
document.write('<A href="/web/kmc/guide/introduce/greeting.jsp">대학소개</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;');
document.write('<A href="/web/kmc/guide/vision/vision.jsp">대학비젼</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;');
document.write('<A href="/web/kmc/guide/admin/organ.jsp">대학행정</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;');
document.write('<A href="/web/kmc/guide/ad/mv.jsp">대학홍보</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;'); 
document.write('<A href="/web/kmc/guide/guide/map.jsp">캠퍼스안내</A> &nbsp;');
document.write('</DIV>');
document.write('<DIV id=submenu_02 style="DISPLAY: none">');
document.write('<A href="/web/kmc/dpguide/hns/a_01.jsp">인문사회계열</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;');
document.write('<A href="/web/kmc/dpguide/nat/b_01.jsp">자연과학계열</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;');
document.write('<A href="/web/kmc/dpguide/eng/c_01.jsp">공업계열</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;');
document.write('<A href="/web/kmc/dpguide/anp/d_01.jsp">예-체능계열</A> &nbsp;');
document.write('</DIV>');
document.write('<DIV id=submenu_03 style="DISPLAY: none">');
document.write('<A href="/web/kmc/support/calendar/default.jsp">학사일정</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;');
document.write('<A href="/web/kmc/support/guide/apply.jsp">학사안내</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;');
document.write('<A href="/web/kmc/support/scholaship/inout.jsp">장학/안내</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;');
document.write('<A href="/web/kmc/support/certificate/apply.jsp">증명서발급</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;');
document.write('<A href="/web/kmc/support/welfare/favor.jsp">학생복지</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;');
document.write('<A href="/web/kmc/support/qna/">질문하기</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;');
document.write('<A href="/web/kmc/support/data/">서식자료실</A> &nbsp;');
document.write('</DIV>');
document.write('<DIV id=submenu_04 style="DISPLAY: none">');
document.write('<A href="#">대학행사</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;');
document.write('<A href="#">캠퍼스일정</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;'); 
document.write('<A href="#">웹진</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;'); 
document.write('<A href="#">학생활동</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;'); 
document.write('<A href="#">편의/복지시설</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;'); 
document.write('<A href="#">학생생활상담</A> &nbsp;');
document.write('</DIV>');
document.write('<DIV id=submenu_05 style="DISPLAY: none">');
document.write('<A href="#">문화공간</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;'); 
document.write('<A href="#">클럽</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;'); 
document.write('<A href="#">테마정보</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;'); 
document.write('<A href="#">생활정보</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;'); 
document.write('<A href="#">참여의장</A> &nbsp;<FONT color=#a0a0a0>|</FONT>&nbsp;'); 
document.write('<A href="#">동문회</A> &nbsp;');
document.write('</DIV>');	
//-->